theme: jekyll-theme-cayman

title: Marquez
description:  >-
  A metadata service for the collection, aggregation,
  and visualization of a data ecosystem's metadata

repository: MarquezProject/marquez
theme: jekyll-theme-cayman

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
